### ISSUE TITLE
feat: addition of `metadata` section to the yaml file specification in RAVEN

### ISSUE THREAD

**Issue by Hao-Chalmers** [SysBioChalmers/RAVEN#311]
### Description of the issue:
* This issue propose to include a `metadata` section to the yaml file specification in RAVEN
    - Previously, a `metadata` section was introduced to the tailored `yaml` file in [Human-GEM](https://github.com/SysBioChalmers/Human-GEM) serving for the requirements of [MetabolicAtlas](https://metabolicatlas.org), as detailed in issue [#71](https://github.com/SysBioChalmers/Human-GEM/issues/71). After continuous development and evolvement, this section functions pretty well in providing relevant information for GEM-type repo (e.g. **Human-GEM**), GEM archive **MetabolicAtals**, as well as the research community.

#### Expected changes:
* Adjust RAVEN model [spec](https://github.com/SysBioChalmers/RAVEN/wiki/RAVEN-Model-Structure) with following changes:
    - Add new field `version`
    - ~Change field from `description` to `fullName`~
    - Modify subfields of `annotation` field
        - adding subfields `sourceUrl`
        - combining `givenName ` and `familyName ` into `authors`
        - ~changing subfield from `note` to `description`~
* Adapt `writeYaml` function to enable the exporting of `metadata` information from fields `id`, ~`fullName`~`name`, `version` and `annotation`

**I hereby confirm that I have:**
- [X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)

**Comment by BenjaSanchez** [comment]
For additional context, below the current `metaData` field in Human-GEM:

```yml
- metaData:
    short_name: "Human-GEM"
    full_name: "Generic genome-scale metabolic model of Homo sapiens"
    version: "1.4.0"
    date: "2020-06-12"
    authors: "Jonathan Robinson, Hao Wang, Pierre-Etienne Cholley, Pinar Kocabas"
    email: "jonrob@chalmers.se"
    organization: "Chalmers University of Technology"
    taxonomy: "9606"
    github: "https://github.com/SysBioChalmers/Human-GEM"
    description: "Genome-scale metabolic models are valuable tools to study metabolism and provide a scaffold for the integrative analysis of omics data. This is the latest version of Human-GEM, which is a genome-scale metabolic model of a generic human cell. The objective of Human-GEM is to serve as a community model for enabling integrative and mechanistic studies of human metabolism."
```

The new fields + modifications sound good to me. Additionally, it would be ideal if the field names in the yaml file match with the RAVEN spec names, for clarity. Below the cases that don't match based on what is already in RAVEN + the new names @Hao-Chalmers proposed:

| Field | Name in RAVEN | Name in `HumanGEM.yml` |
|:-:|:-:|:-:|
| Model id | `id` | `short_name` |
| Model name | `description` | `full_name` |
| Authors | `annotation.authorList` | `authors` |
| URL where the model lives | `annotation.sourceUrl` | `github` |
| Additional comments | `annotation.note` | `description` |

IMO the RAVEN names for id and URL would be preferable, as the former is the main choice in the COBRA community (Matlab and Python), and the latter is more generic, as not all RAVEN models are stored in Github. Could those 2 fields change in `HumanGEM.yml` to `id` and `source_url`? @JonathanRob @mihai-sysbio 

On the other side, the `.yml` standard seems more adequate for model name, authors and comments (actually it's super confusing that the RAVEN field `description` is the model name and the field `note` contains a description). Would it make sense to change those 3 fields in RAVEN to `fullName`, `annotation.authors` and `annotation.description`?
